In [2]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

In [7]:
X, Y = make_regression()

In [8]:
X.shape

(100, 100)

In [9]:
Y.shape

(100,)

### Splitting our dataset into train/test sets 

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42)

In [12]:
X_test.shape

(25, 100)

### Train the Regressor! 

$$ y = \beta X + \epsilon$$

predicted:

$$ \hat{y} = f(X) = \hat{\beta} X $$

In [13]:
# initialize our regressor object
reg = LinearRegression()

In [14]:
# train the model
reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
# betas
reg.coef_

array([ -6.66813258e+00,   9.63658751e+00,   8.52519826e+01,
         2.21036084e+01,   5.51977852e+00,   7.94430633e+00,
        -1.27053416e+01,  -2.81699696e+00,   2.19125340e+00,
         6.11923318e+00,   7.37616001e+00,   8.54624367e+00,
        -5.87348162e+00,  -2.40520841e+01,   4.63272494e+00,
         8.89729247e-01,   1.13325757e+01,  -5.80458757e+00,
        -6.66614752e+00,   1.26982699e+01,   5.55040854e+00,
         9.22811459e+00,   6.00696134e+01,  -7.69397904e+00,
         1.81293054e+01,  -4.44376221e+00,   2.75817444e-02,
        -1.04918267e+00,  -7.99904335e+00,  -8.88124979e+00,
        -8.28054501e-01,   1.12441437e+01,  -1.12345590e+01,
         4.73072500e+00,  -6.33390106e+00,  -3.15823662e+00,
        -7.23110519e+00,  -6.18079179e+00,  -5.59717367e+00,
        -6.01925079e+00,  -1.66441497e+00,  -1.54254481e+01,
         1.23225962e+00,  -2.95339842e+00,  -2.71500493e+00,
        -2.99730014e+00,   1.23286866e+01,   5.56540470e+00,
         6.19927170e+00,

### Predict on the test data 

In [18]:
y_test_predicted = reg.predict(X_test)

In [19]:
y_test

array([ 247.73172777,  -34.88129585,   18.93765081,  -93.50168546,
       -118.14313985,  -85.81539809, -173.99515528,  301.88488537,
          1.13676145, -231.62557168,  161.22530565,  -51.81006009,
        261.72078331,  -43.55829526,  141.18602089, -185.73826924,
         85.61991103,  264.13539784,  257.58454739, -375.81563071,
         55.29361013,  -52.56343375,    3.29243411,   83.04120241,
        -16.0835407 ])

In [20]:
y_test_predicted

array([ 199.05670309,   31.76427738,  -67.54235394,  -46.66422697,
         59.49448647, -150.39697464,  -94.98957795,  184.87363669,
       -134.08463658, -222.88771539,  158.28479016,  -23.71783506,
        214.11982582,  -48.29268977,   16.43048614,  -69.91204636,
         91.36985228,  135.53877228,  342.0451449 , -239.37783127,
        139.13232568,  -47.28934229,  -26.04210693,  218.0794353 ,
         98.00227076])

In [25]:
mse = ((y_test - y_test_predicted)**2).sum()

In [26]:
mse

204056.94629539628